<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>ScreenLock</RootNamespace>
    <AssemblyName>ScreenLock</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ApplicationIcon>Assets\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Icon.ico" />
    <Resource Include="Assets\Icon.png" />
  </ItemGroup>

</Project>
